# Generated by Django 6.0.5 on 2026-06-10 10:03

import apps.media_manager.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document')], max_length=20)),
                ('category', models.CharField(choices=[('avatar', 'Avatar'), ('building_image', 'Building Image'), ('complaint_attachment', 'Complaint Attachment'), ('notice_attachment', 'Notice Attachment')], max_length=50)),
                ('file', models.FileField(upload_to=apps.media_manager.models.media_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.BigIntegerField(default=0)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'media',
                'ordering': ['display_order', '-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='media_content_a5c40c_idx'), models.Index(fields=['category'], name='media_categor_ad2006_idx')],
            },
        ),
    ]
