# Generated by Django 6.0.5 on 2026-05-31 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0002_building_society_email_building_society_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wing', models.CharField(max_length=10)),
                ('flat_number', models.CharField(max_length=20)),
                ('floor_number', models.PositiveIntegerField()),
                ('flat_type', models.CharField(max_length=50)),
                ('occupancy_status', models.CharField(choices=[('occupied', 'Occupied'), ('vacant', 'Vacant')], default='vacant', max_length=10)),
                ('area_sqft', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='building.building')),
            ],
            options={
                'db_table': 'flats',
                'ordering': ['wing', 'flat_number'],
                'unique_together': {('building', 'wing', 'flat_number')},
            },
        ),
    ]
