# Generated by Django 6.0.5 on 2026-06-03 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0003_alter_building_options_remove_building_total_flats_and_more'),
        ('flats', '0001_initial'),
        ('wing', '0002_alter_wing_options_wing_created_at_wing_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flat',
            options={'ordering': ['wing__wing_name', 'floor_number', 'flat_number']},
        ),
        migrations.AlterUniqueTogether(
            name='flat',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='flat',
            name='flat_type',
            field=models.CharField(choices=[('1RK', '1 RK'), ('1BHK', '1 BHK'), ('2BHK', '2 BHK'), ('3BHK', '3 BHK'), ('4BHK', '4 BHK'), ('5BHK', '5 BHK'), ('SHOP', 'Shop'), ('OFFICE', 'Office'), ('COMMERCIAL', 'Commercial Unit'), ('WAREHOUSE', 'Warehouse')], max_length=20),
        ),
        migrations.AlterField(
            model_name='flat',
            name='occupancy_status',
            field=models.CharField(choices=[('occupied', 'Occupied'), ('vacant', 'Vacant'), ('unsold', 'Unsold')], default='unsold', max_length=20),
        ),
        migrations.AlterField(
            model_name='flat',
            name='wing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flats', to='wing.wing'),
        ),
        migrations.AddIndex(
            model_name='flat',
            index=models.Index(fields=['building'], name='flats_buildin_18c0e3_idx'),
        ),
        migrations.AddIndex(
            model_name='flat',
            index=models.Index(fields=['wing'], name='flats_wing_id_1c2d24_idx'),
        ),
        migrations.AddIndex(
            model_name='flat',
            index=models.Index(fields=['flat_number'], name='flats_flat_nu_4157dd_idx'),
        ),
        migrations.AddIndex(
            model_name='flat',
            index=models.Index(fields=['occupancy_status'], name='flats_occupan_cfc8df_idx'),
        ),
        migrations.AddIndex(
            model_name='flat',
            index=models.Index(fields=['is_active'], name='flats_is_acti_2325f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='flat',
            constraint=models.UniqueConstraint(fields=('building', 'wing', 'flat_number'), name='unique_flat_per_wing'),
        ),
    ]
