# Generated by Django 6.0.5 on 2026-06-10 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0001_initial'),
        ('flats', '0001_initial'),
        ('wing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flat',
            name='wing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flats', to='wing.wing'),
        ),
        migrations.AddField(
            model_name='flattype',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flat_types', to='building.building'),
        ),
        migrations.AddField(
            model_name='flat',
            name='flat_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flats', to='flats.flattype'),
        ),
        migrations.AddIndex(
            model_name='flattype',
            index=models.Index(fields=['building'], name='flat_types_buildin_1be01c_idx'),
        ),
        migrations.AddIndex(
            model_name='flattype',
            index=models.Index(fields=['is_active'], name='flat_types_is_acti_9fbc69_idx'),
        ),
        migrations.AddConstraint(
            model_name='flattype',
            constraint=models.UniqueConstraint(fields=('building', 'name'), name='unique_flat_type_per_building'),
        ),
        migrations.AddIndex(
            model_name='flat',
            index=models.Index(fields=['building'], name='flats_buildin_18c0e3_idx'),
        ),
        migrations.AddIndex(
            model_name='flat',
            index=models.Index(fields=['wing'], name='flats_wing_id_1c2d24_idx'),
        ),
        migrations.AddIndex(
            model_name='flat',
            index=models.Index(fields=['flat_number'], name='flats_flat_nu_4157dd_idx'),
        ),
        migrations.AddIndex(
            model_name='flat',
            index=models.Index(fields=['occupancy_status'], name='flats_occupan_cfc8df_idx'),
        ),
        migrations.AddIndex(
            model_name='flat',
            index=models.Index(fields=['is_active'], name='flats_is_acti_2325f7_idx'),
        ),
        migrations.AddIndex(
            model_name='flat',
            index=models.Index(fields=['flat_type'], name='flats_flat_ty_afc328_idx'),
        ),
        migrations.AddConstraint(
            model_name='flat',
            constraint=models.UniqueConstraint(fields=('building', 'wing', 'flat_number'), name='unique_flat_per_wing'),
        ),
    ]
