# Generated by Django 6.0.5 on 2026-06-10 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('notice_type', models.CharField(choices=[('general', 'General'), ('maintenance', 'Maintenance'), ('meeting', 'Meeting'), ('event', 'Event'), ('emergency', 'Emergency')], default='general', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='building.building')),
            ],
            options={
                'db_table': 'notices',
                'ordering': ['-created_at'],
            },
        ),
    ]
