# Generated by Django 6.0.5 on 2026-06-10 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['building'], name='notices_buildin_73a744_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['notice_type'], name='notices_notice__ba5e8d_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['is_active'], name='notices_is_acti_6c2158_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['start_date'], name='notices_start_d_e29e37_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['end_date'], name='notices_end_dat_901af5_idx'),
        ),
    ]
