# Generated by Django 6.0.5 on 2026-05-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
