# Generated by Django 6.0.5 on 2026-05-26 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
        ('users', '0002_user_reset_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='building_id',
        ),
        migrations.AddField(
            model_name='user',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='building.building'),
        ),
    ]
