# Generated by Django 6.0.5 on 2026-06-10 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0001_initial'),
        ('flats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(choices=[('opening', 'Opening Due'), ('monthly', 'Monthly Maintenance'), ('special', 'Special Charge')], default='monthly', max_length=20)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pending_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('generated_on', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_bills', to='flats.flat')),
            ],
            options={
                'db_table': 'maintenance_bills',
                'ordering': ['-year', '-month', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_type', models.CharField(choices=[('fixed', 'Fixed'), ('per_sqft', 'Per Sqft')], max_length=20)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate_per_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('effective_from', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_configs', to='building.building')),
            ],
            options={
                'db_table': 'maintenance_configs',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unallocated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('receipt_number', models.CharField(max_length=100, null=True, unique=True)),
                ('payment_mode', models.CharField(choices=[('online', 'Online'), ('cash', 'Cash'), ('cheque', 'Cheque')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('paid_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='flats.flat')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjusted_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='maintenance.maintenancebill')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='maintenance.payment')),
            ],
            options={
                'db_table': 'payment_adjustments',
            },
        ),
        migrations.AddIndex(
            model_name='maintenancebill',
            index=models.Index(fields=['flat'], name='maintenance_flat_id_752dd7_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancebill',
            index=models.Index(fields=['status'], name='maintenance_status_5380ba_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancebill',
            index=models.Index(fields=['year'], name='maintenance_year_2e3d85_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancebill',
            index=models.Index(fields=['month'], name='maintenance_month_2372c7_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancebill',
            index=models.Index(fields=['is_active'], name='maintenance_is_acti_21e4a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='maintenancebill',
            constraint=models.UniqueConstraint(fields=('flat', 'bill_type', 'month', 'year'), name='unique_bill_per_month'),
        ),
        migrations.AddIndex(
            model_name='maintenanceconfig',
            index=models.Index(fields=['building'], name='maintenance_buildin_12544e_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceconfig',
            index=models.Index(fields=['effective_from'], name='maintenance_effecti_7f22c1_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceconfig',
            index=models.Index(fields=['is_active'], name='maintenance_is_acti_61108e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['flat'], name='payments_flat_id_a97b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['receipt_number'], name='payments_receipt_6cb761_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paid_at'], name='payments_paid_at_c989bb_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['is_active'], name='payments_is_acti_308c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentadjustment',
            index=models.Index(fields=['payment'], name='payment_adj_payment_2b09a2_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentadjustment',
            index=models.Index(fields=['bill'], name='payment_adj_bill_id_86a5ae_idx'),
        ),
    ]
