# Generated by Django 6.0.5 on 2026-06-02 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0003_alter_building_options_remove_building_total_flats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_type', models.CharField(choices=[('fixed', 'Fixed'), ('per_sqft', 'Per Sqft')], max_length=20)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate_per_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('effective_from', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_configs', to='building.building')),
            ],
            options={
                'db_table': 'maintenance_configs',
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['building'], name='maintenance_buildin_12544e_idx'), models.Index(fields=['effective_from'], name='maintenance_effecti_7f22c1_idx'), models.Index(fields=['is_active'], name='maintenance_is_acti_61108e_idx')],
            },
        ),
    ]
