# Generated by Django 6.0.5 on 2026-06-02 12:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0003_alter_building_options_remove_building_total_flats_and_more'),
        ('flats', '0001_initial'),
        ('maintenance', '0002_maintenancebill_payment_paymentadjustment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-paid_at']},
        ),
        migrations.AddField(
            model_name='maintenancebill',
            name='generated_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='maintenancebill',
            index=models.Index(fields=['flat'], name='maintenance_flat_id_752dd7_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancebill',
            index=models.Index(fields=['status'], name='maintenance_status_5380ba_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancebill',
            index=models.Index(fields=['year'], name='maintenance_year_2e3d85_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancebill',
            index=models.Index(fields=['month'], name='maintenance_month_2372c7_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancebill',
            index=models.Index(fields=['is_active'], name='maintenance_is_acti_21e4a1_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceconfig',
            index=models.Index(fields=['building'], name='maintenance_buildin_12544e_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceconfig',
            index=models.Index(fields=['effective_from'], name='maintenance_effecti_7f22c1_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceconfig',
            index=models.Index(fields=['is_active'], name='maintenance_is_acti_61108e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['flat'], name='payments_flat_id_a97b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['receipt_number'], name='payments_receipt_6cb761_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paid_at'], name='payments_paid_at_c989bb_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['is_active'], name='payments_is_acti_308c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentadjustment',
            index=models.Index(fields=['payment'], name='payment_adj_payment_2b09a2_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentadjustment',
            index=models.Index(fields=['bill'], name='payment_adj_bill_id_86a5ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='maintenancebill',
            constraint=models.UniqueConstraint(fields=('flat', 'bill_type', 'month', 'year'), name='unique_bill_per_month'),
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payments',
        ),
    ]
