# Generated by Django 6.0.5 on 2026-06-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_payment_options_maintenancebill_generated_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='unallocated_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
