# Generated by Django 6.0.5 on 2026-06-02 11:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0003_alter_building_options_remove_building_total_flats_and_more'),
        ('wing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wing',
            options={'ordering': ['wing_name']},
        ),
        migrations.AddField(
            model_name='wing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wing',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='wing',
            constraint=models.UniqueConstraint(fields=('building', 'wing_name'), name='unique_wing_per_building'),
        ),
        migrations.AlterModelTable(
            name='wing',
            table='wings',
        ),
    ]
