# Generated by Django 6.0.5 on 2026-06-10 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaint', '0001_initial'),
        ('flats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='flats.flat'),
        ),
    ]
