# Generated by Django 6.0.5 on 2026-06-10 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaint', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['building'], name='complaints_buildin_1152ea_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['flat'], name='complaints_flat_id_a3edf7_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['user'], name='complaints_user_id_b04828_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status'], name='complaints_status_3d57ee_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['created_at'], name='complaints_created_a37218_idx'),
        ),
    ]
