# Generated by Django 6.0.5 on 2026-06-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=255)),
                ('building_code', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('total_floors', models.PositiveIntegerField(default=0)),
                ('society_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('society_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('building_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], default='residential', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'buildings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['building_code'], name='buildings_buildin_d0e10f_idx'), models.Index(fields=['city'], name='buildings_city_f0e2cf_idx'), models.Index(fields=['is_active'], name='buildings_is_acti_1def2d_idx')],
            },
        ),
    ]
