# Generated by Django 6.0.5 on 2026-05-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='society_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='society_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
