# Generated by Django 6.0.5 on 2026-06-02 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0002_building_society_email_building_society_mobile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='building',
            name='total_flats',
        ),
        migrations.AlterField(
            model_name='building',
            name='total_floors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['building_code'], name='buildings_buildin_d0e10f_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['city'], name='buildings_city_f0e2cf_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['is_active'], name='buildings_is_acti_1def2d_idx'),
        ),
        migrations.AlterModelTable(
            name='building',
            table='buildings',
        ),
    ]
