# Generated by Django 6.0.5 on 2026-06-10 10:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_type', models.CharField(db_index=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('description', models.TextField(blank=True)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('income_date', models.DateField(db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='building.building')),
            ],
            options={
                'db_table': 'incomes',
                'ordering': ['-income_date', '-id'],
                'indexes': [models.Index(fields=['building', 'income_date'], name='incomes_buildin_773a10_idx'), models.Index(fields=['income_type'], name='incomes_income__7265ea_idx'), models.Index(fields=['is_deleted'], name='incomes_is_dele_120fd4_idx')],
            },
        ),
    ]
