# Generated by Django 6.0.5 on 2026-06-10 10:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(db_index=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('description', models.TextField(blank=True)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('expense_date', models.DateField(db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='building.building')),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-expense_date', '-id'],
                'indexes': [models.Index(fields=['building', 'expense_date'], name='expenses_buildin_e46e25_idx'), models.Index(fields=['expense_type'], name='expenses_expense_272666_idx'), models.Index(fields=['is_deleted'], name='expenses_is_dele_0645ac_idx')],
            },
        ),
    ]
